name: GitLab to GitHub migration
description: Perform a migration from GitLab to GitHub
title: "GitLab to GitHub migration"
labels: ["migration", "gitlab"]
body:
  - type: textarea
    id: repositories
    attributes:
      label: Repositories
      description: Please enter the repositories that you would like to migrate from GitLab to GitHub
      placeholder: |
        group1,repo1
        group2,repo2
    validations:
      required: true
  - type: dropdown
    id: visibility
    attributes:
      label: Target repository visibility
      description: Please select the visibility for the repositories on GitHub after they have been migrated
      options:
        - Private
        - Internal
    validations:
      required: true
