name: GitLab repos to GitHub Migration [GEI]
description: Perform a migration of repos from GitLab or GHEC to GitHub using GEI (gh glx-migrator)
title: "gitlab repos to GitHub migration [GEI]"
labels: ["migration", "gei-gitlab"]
body:
  - type: textarea
    id: repositories
    attributes:
      label: Repositories
      description: Please enter the repositories that you would like to migrate from GitHub Enterprise Server to GitHub Enterprise Cloud
      placeholder: |
        group1,repo1
        group2/sub-group1,repo2
    validations:
      required: true
  - type: dropdown
    id: visibility
    attributes:
      label: Target repository visibility
      description: Please select the visibility for the repositories on GitHub Enterprise Cloud after they have been migrated
      options:
        - Private
        - Internal
        - Mirror
    validations:
      required: true
